### ISSUE TITLE
Rails recipe app: Set up Kanban board

### ISSUE THREAD

**Issue by okoyecharles** [OkoyeCharles/rails-recipe-app#13]
## Description ✍🏽
In this activity, we prepared a Kanban board with a GitHub project. We created this Kanban board from scratch. Our job was to translate project requirements into separate tasks and to create a card for each task.
Here is the [Project Board Link](https://github.com/OkoyeCharles/rails-recipe-app/projects/1)

## Changes Made ♻️
Each line below are required changes asked to be implemented by microverse and/or additional changes
- [x] Create a new repository.
- [x] Setup a Kanban board from scratch
- [x] Create tasks based on the project requirements
- [x] Assign each other to created tasks
- [x] Resolve errors

### Participants (2 team members)
* @OkoyeCharles
* @Bria222 

### Comments
Feel free to leave any comments in the PR thread if something is not 100% clear.
### Optional Suggestions
If you notice a problem that is not crucial enough to stop the approval of this PR. However, you strongly recommend I take them into account. Please I would love it if you let me know
### Clarity
Please it would be a pleasure if you could be as clear and precise as possible, as we have only three review attempts.
Thanks for understanding.

---------
_If there are any issues you would like to discuss quickly, you could contact me on [Slack](https://app.slack.com/client/T47CT8XPG/D039GHCKW3F), or (occasionally) on [WhatsApp](https://wa.me/+2348032533432)_

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good setup

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
